"""add source_image_bytes

Revision ID: cd30397b4b1f
Revises: 0004_projects_waitlist
Create Date: 2026-06-25 20:26:20.199650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd30397b4b1f'
down_revision: Union[str, None] = '0004_projects_waitlist'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aaas_api_keys', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment="Human-readable label, e.g. 'Production iOS SDK'",
               existing_nullable=False)
    op.alter_column('aaas_api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment='First 12 chars of key used for DB lookup',
               existing_nullable=False)
    op.alter_column('aaas_api_keys', 'hashed_secret',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash of the full API key — plaintext never stored',
               existing_nullable=False)
    op.alter_column('aaas_api_keys', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='List of permitted scopes',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('aaas_api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of most recent successful authentication',
               existing_nullable=True)
    op.alter_column('aaas_api_keys', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active | revoked | rotated',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_aaas_api_keys_application_id'), 'aaas_api_keys', ['application_id'], unique=False)
    op.alter_column('applications', 'environment',
               existing_type=sa.VARCHAR(length=50),
               comment='development | staging | production',
               existing_nullable=False,
               existing_server_default=sa.text("'production'::character varying"))
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active | inactive | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('audit_events', 'actor_id',
               existing_type=sa.UUID(),
               comment='Platform user who triggered this event; null for automated actions',
               existing_nullable=True)
    op.alter_column('audit_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment='e.g. identity.enrolled, api_key.created, liveness.failed',
               existing_nullable=False)
    op.alter_column('audit_events', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Type of affected entity, e.g. 'identity', 'api_key'",
               existing_nullable=True)
    op.alter_column('audit_events', 'entity_id',
               existing_type=sa.VARCHAR(length=255),
               comment='UUID string of the affected entity',
               existing_nullable=True)
    op.alter_column('audit_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Event-specific context as JSONB',
               existing_nullable=True)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_application_id'), 'audit_events', ['application_id'], unique=False)
    op.alter_column('authentication_sessions', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment='enrollment | verification | liveness | authentication',
               existing_nullable=False)
    op.alter_column('authentication_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='success | failure | pending | challenge',
               existing_nullable=False)
    op.alter_column('authentication_sessions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Biometric match confidence 0.0–1.0',
               existing_nullable=True)
    op.alter_column('authentication_sessions', 'risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Trust Engine risk score 0.0–100.0',
               existing_nullable=True)
    op.alter_column('authentication_sessions', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='End-to-end processing time in milliseconds',
               existing_nullable=True)
    op.drop_index('ix_auth_sessions_application_id', table_name='authentication_sessions')
    op.drop_index('ix_auth_sessions_created_at', table_name='authentication_sessions')
    op.drop_index('ix_auth_sessions_event_type', table_name='authentication_sessions')
    op.drop_index('ix_auth_sessions_identity_id', table_name='authentication_sessions')
    op.drop_index('ix_auth_sessions_organization_id', table_name='authentication_sessions')
    op.drop_index('ix_auth_sessions_status', table_name='authentication_sessions')
    op.create_index(op.f('ix_authentication_sessions_application_id'), 'authentication_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_authentication_sessions_created_at'), 'authentication_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_authentication_sessions_event_type'), 'authentication_sessions', ['event_type'], unique=False)
    op.create_index(op.f('ix_authentication_sessions_identity_id'), 'authentication_sessions', ['identity_id'], unique=False)
    op.create_index(op.f('ix_authentication_sessions_organization_id'), 'authentication_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_authentication_sessions_status'), 'authentication_sessions', ['status'], unique=False)
    op.alter_column('behavior_events', 'event_type',
               existing_type=sa.VARCHAR(length=30),
               comment='mouse | keyboard | touch',
               existing_nullable=False)
    op.alter_column('behavior_events', 'anomaly_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='IsolationForest anomaly score',
               existing_nullable=True)
    op.drop_constraint('uq_behavior_profiles_user_id', 'behavior_profiles', type_='unique')
    op.drop_index('ix_behavior_profiles_user_id', table_name='behavior_profiles')
    op.create_index(op.f('ix_behavior_profiles_user_id'), 'behavior_profiles', ['user_id'], unique=True)
    op.alter_column('challenge_logs', 'challenge_type',
               existing_type=sa.VARCHAR(length=200),
               comment='e.g. blink_twice, turn_left_smile, open_mouth_blink',
               existing_nullable=False)
    op.alter_column('challenge_logs', 'challenge_steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Ordered list of actions',
               existing_nullable=True)
    op.alter_column('continuous_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='active | suspended | terminated | reauth_required',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint('uq_continuous_sessions_session_token', 'continuous_sessions', type_='unique')
    op.drop_index('ix_continuous_sessions_session_token', table_name='continuous_sessions')
    op.create_index(op.f('ix_continuous_sessions_session_token'), 'continuous_sessions', ['session_token'], unique=True)
    op.alter_column('deepfake_logs', 'deepfake_probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0.0–1.0',
               existing_nullable=False)
    op.alter_column('deepfake_logs', 'model_used',
               existing_type=sa.VARCHAR(length=50),
               comment='efficientnet_b4 | xceptionnet | heuristic',
               existing_nullable=True)
    op.alter_column('deepfake_logs', 'attack_category',
               existing_type=sa.VARCHAR(length=50),
               comment='face_swap | gan_face | synthetic_avatar | deepfake_video | none',
               existing_nullable=True)
    op.alter_column('deepfake_logs', 'image_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='SHA-256 of analyzed frame (not stored)',
               existing_nullable=True)
    op.alter_column('device_trust_logs', 'device_platform',
               existing_type=sa.VARCHAR(length=20),
               comment='android | ios | web',
               existing_nullable=True)
    op.alter_column('emotion_logs', 'emotion',
               existing_type=sa.VARCHAR(length=20),
               comment='happy | neutral | surprise | angry | sad | fear | disgust',
               existing_nullable=False)
    op.alter_column('emotion_logs', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0–100',
               existing_nullable=False)
    op.alter_column('emotion_logs', 'all_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Per-class probabilities',
               existing_nullable=True)
    op.add_column('face_embeddings', sa.Column('source_image_bytes', sa.LargeBinary(), nullable=True, comment='Raw source enrollment image bytes (JPEG or PNG)'))
    op.add_column('fingerprint_templates', sa.Column('source_image_bytes', sa.LargeBinary(), nullable=True, comment='Raw source fingerprint image bytes'))
    op.alter_column('headpose_logs', 'pitch',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Degrees, positive=up',
               existing_nullable=True)
    op.alter_column('headpose_logs', 'roll',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Degrees, positive=clockwise',
               existing_nullable=True)
    op.alter_column('headpose_logs', 'yaw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Degrees, positive=right',
               existing_nullable=True)
    op.alter_column('identities', 'external_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment="Customer's own user identifier",
               existing_nullable=False)
    op.alter_column('identities', 'enrollment_status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending | enrolled | failed | revoked',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_identities_face_embedding_id'), 'identities', ['face_embedding_id'], unique=False)
    op.add_column('iris_embeddings', sa.Column('source_image_bytes', sa.LargeBinary(), nullable=True, comment='Raw source enrollment image bytes (JPEG or PNG)'))
    op.alter_column('liveness_logs', 'liveness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0.0–1.0',
               existing_nullable=True)
    op.alter_column('liveness_logs', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='0–100',
               existing_nullable=True)
    op.alter_column('liveness_logs', 'check_type',
               existing_type=sa.VARCHAR(length=20),
               comment='passive | active',
               existing_nullable=False,
               existing_server_default=sa.text("'passive'::character varying"))
    op.alter_column('liveness_logs', 'challenge_type',
               existing_type=sa.VARCHAR(length=100),
               comment='e.g. blink_twice, turn_left_smile',
               existing_nullable=True)
    op.alter_column('model_versions', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='e.g. face_recognition, liveness, anti_spoof, deepfake',
               existing_nullable=False)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment="Semver or date-based version string, e.g. '2.1.0'",
               existing_nullable=False)
    op.alter_column('model_versions', 'accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Top-1 accuracy on internal eval set',
               existing_nullable=True)
    op.alter_column('model_versions', 'far',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='False Acceptance Rate',
               existing_nullable=True)
    op.alter_column('model_versions', 'frr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='False Rejection Rate',
               existing_nullable=True)
    op.alter_column('model_versions', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='Median inference latency in milliseconds',
               existing_nullable=True)
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active | shadow | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('model_versions', 'deployed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this version was promoted to active',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('org_memberships', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment='owner | admin | member',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               comment='Organization unique identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Display name',
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment="URL-safe unique identifier, e.g. 'acme-corp'",
               existing_nullable=False)
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=50),
               comment='Subscription plan: free | starter | pro | enterprise',
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Lifecycle status: active | suspended | trial | cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_constraint('uq_organizations_slug', 'organizations', type_='unique')
    op.alter_column('risk_scores', 'deepfake_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Inverted: 100 = no deepfake',
               existing_nullable=True)
    op.alter_column('risk_scores', 'decision',
               existing_type=sa.VARCHAR(length=20),
               comment='approve | step_up | reject',
               existing_nullable=False)
    op.alter_column('usage_records', 'endpoint',
               existing_type=sa.VARCHAR(length=100),
               comment="API endpoint path, e.g. '/api/v1/identities'",
               existing_nullable=False)
    op.alter_column('usage_records', 'bucket_date',
               existing_type=sa.DATE(),
               comment='UTC date of the aggregation bucket',
               existing_nullable=False)
    op.create_index(op.f('ix_usage_records_application_id'), 'usage_records', ['application_id'], unique=False)
    op.alter_column('webhook_deliveries', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Full event payload sent to the endpoint',
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='pending | success | failed | retrying',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('webhook_deliveries', 'http_status',
               existing_type=sa.INTEGER(),
               comment='HTTP response status code from the destination',
               existing_nullable=True)
    op.alter_column('webhook_deliveries', 'attempts',
               existing_type=sa.INTEGER(),
               comment='Number of delivery attempts made so far',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('webhook_endpoints', 'url',
               existing_type=sa.TEXT(),
               comment='Destination URL for POST delivery',
               existing_nullable=False)
    op.alter_column('webhook_endpoints', 'signing_secret',
               existing_type=sa.VARCHAR(length=255),
               comment='HMAC-SHA256 signing secret (stored encrypted at rest)',
               existing_nullable=False)
    op.alter_column('webhook_endpoints', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Subscribed event types',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('webhook_endpoints', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active | paused | disabled',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_webhook_endpoints_application_id'), 'webhook_endpoints', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_endpoints_application_id'), table_name='webhook_endpoints')
    op.alter_column('webhook_endpoints', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='active | paused | disabled',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('webhook_endpoints', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Subscribed event types',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('webhook_endpoints', 'signing_secret',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='HMAC-SHA256 signing secret (stored encrypted at rest)',
               existing_nullable=False)
    op.alter_column('webhook_endpoints', 'url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Destination URL for POST delivery',
               existing_nullable=False)
    op.alter_column('webhook_deliveries', 'attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of delivery attempts made so far',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('webhook_deliveries', 'http_status',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='HTTP response status code from the destination',
               existing_nullable=True)
    op.alter_column('webhook_deliveries', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending | success | failed | retrying',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('webhook_deliveries', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Full event payload sent to the endpoint',
               existing_nullable=False)
    op.drop_index(op.f('ix_usage_records_application_id'), table_name='usage_records')
    op.alter_column('usage_records', 'bucket_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='UTC date of the aggregation bucket',
               existing_nullable=False)
    op.alter_column('usage_records', 'endpoint',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="API endpoint path, e.g. '/api/v1/identities'",
               existing_nullable=False)
    op.alter_column('risk_scores', 'decision',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='approve | step_up | reject',
               existing_nullable=False)
    op.alter_column('risk_scores', 'deepfake_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Inverted: 100 = no deepfake',
               existing_nullable=True)
    op.create_unique_constraint('uq_organizations_slug', 'organizations', ['slug'])
    op.alter_column('organizations', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Lifecycle status: active | suspended | trial | cancelled',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('organizations', 'plan',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Subscription plan: free | starter | pro | enterprise',
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="URL-safe unique identifier, e.g. 'acme-corp'",
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Display name',
               existing_nullable=False)
    op.alter_column('organizations', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Organization unique identifier',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('org_memberships', 'role',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='owner | admin | member',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.alter_column('model_versions', 'deployed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this version was promoted to active',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='active | shadow | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('model_versions', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Median inference latency in milliseconds',
               existing_nullable=True)
    op.alter_column('model_versions', 'frr',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='False Rejection Rate',
               existing_nullable=True)
    op.alter_column('model_versions', 'far',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='False Acceptance Rate',
               existing_nullable=True)
    op.alter_column('model_versions', 'accuracy',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Top-1 accuracy on internal eval set',
               existing_nullable=True)
    op.alter_column('model_versions', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Semver or date-based version string, e.g. '2.1.0'",
               existing_nullable=False)
    op.alter_column('model_versions', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='e.g. face_recognition, liveness, anti_spoof, deepfake',
               existing_nullable=False)
    op.alter_column('liveness_logs', 'challenge_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='e.g. blink_twice, turn_left_smile',
               existing_nullable=True)
    op.alter_column('liveness_logs', 'check_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='passive | active',
               existing_nullable=False,
               existing_server_default=sa.text("'passive'::character varying"))
    op.alter_column('liveness_logs', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0–100',
               existing_nullable=True)
    op.alter_column('liveness_logs', 'liveness_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0.0–1.0',
               existing_nullable=True)
    op.drop_column('iris_embeddings', 'source_image_bytes')
    op.drop_index(op.f('ix_identities_face_embedding_id'), table_name='identities')
    op.alter_column('identities', 'enrollment_status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='pending | enrolled | failed | revoked',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('identities', 'external_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Customer's own user identifier",
               existing_nullable=False)
    op.alter_column('headpose_logs', 'yaw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Degrees, positive=right',
               existing_nullable=True)
    op.alter_column('headpose_logs', 'roll',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Degrees, positive=clockwise',
               existing_nullable=True)
    op.alter_column('headpose_logs', 'pitch',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Degrees, positive=up',
               existing_nullable=True)
    op.drop_column('fingerprint_templates', 'source_image_bytes')
    op.drop_column('face_embeddings', 'source_image_bytes')
    op.alter_column('emotion_logs', 'all_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Per-class probabilities',
               existing_nullable=True)
    op.alter_column('emotion_logs', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0–100',
               existing_nullable=False)
    op.alter_column('emotion_logs', 'emotion',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='happy | neutral | surprise | angry | sad | fear | disgust',
               existing_nullable=False)
    op.alter_column('device_trust_logs', 'device_platform',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='android | ios | web',
               existing_nullable=True)
    op.alter_column('deepfake_logs', 'image_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='SHA-256 of analyzed frame (not stored)',
               existing_nullable=True)
    op.alter_column('deepfake_logs', 'attack_category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='face_swap | gan_face | synthetic_avatar | deepfake_video | none',
               existing_nullable=True)
    op.alter_column('deepfake_logs', 'model_used',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='efficientnet_b4 | xceptionnet | heuristic',
               existing_nullable=True)
    op.alter_column('deepfake_logs', 'deepfake_probability',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='0.0–1.0',
               existing_nullable=False)
    op.drop_index(op.f('ix_continuous_sessions_session_token'), table_name='continuous_sessions')
    op.create_index('ix_continuous_sessions_session_token', 'continuous_sessions', ['session_token'], unique=False)
    op.create_unique_constraint('uq_continuous_sessions_session_token', 'continuous_sessions', ['session_token'])
    op.alter_column('continuous_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='active | suspended | terminated | reauth_required',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('challenge_logs', 'challenge_steps',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Ordered list of actions',
               existing_nullable=True)
    op.alter_column('challenge_logs', 'challenge_type',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='e.g. blink_twice, turn_left_smile, open_mouth_blink',
               existing_nullable=False)
    op.drop_index(op.f('ix_behavior_profiles_user_id'), table_name='behavior_profiles')
    op.create_index('ix_behavior_profiles_user_id', 'behavior_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('uq_behavior_profiles_user_id', 'behavior_profiles', ['user_id'])
    op.alter_column('behavior_events', 'anomaly_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='IsolationForest anomaly score',
               existing_nullable=True)
    op.alter_column('behavior_events', 'event_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='mouse | keyboard | touch',
               existing_nullable=False)
    op.drop_index(op.f('ix_authentication_sessions_status'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_organization_id'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_identity_id'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_event_type'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_created_at'), table_name='authentication_sessions')
    op.drop_index(op.f('ix_authentication_sessions_application_id'), table_name='authentication_sessions')
    op.create_index('ix_auth_sessions_status', 'authentication_sessions', ['status'], unique=False)
    op.create_index('ix_auth_sessions_organization_id', 'authentication_sessions', ['organization_id'], unique=False)
    op.create_index('ix_auth_sessions_identity_id', 'authentication_sessions', ['identity_id'], unique=False)
    op.create_index('ix_auth_sessions_event_type', 'authentication_sessions', ['event_type'], unique=False)
    op.create_index('ix_auth_sessions_created_at', 'authentication_sessions', ['created_at'], unique=False)
    op.create_index('ix_auth_sessions_application_id', 'authentication_sessions', ['application_id'], unique=False)
    op.alter_column('authentication_sessions', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='End-to-end processing time in milliseconds',
               existing_nullable=True)
    op.alter_column('authentication_sessions', 'risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Trust Engine risk score 0.0–100.0',
               existing_nullable=True)
    op.alter_column('authentication_sessions', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Biometric match confidence 0.0–1.0',
               existing_nullable=True)
    op.alter_column('authentication_sessions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='success | failure | pending | challenge',
               existing_nullable=False)
    op.alter_column('authentication_sessions', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='enrollment | verification | liveness | authentication',
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_events_application_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.alter_column('audit_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Event-specific context as JSONB',
               existing_nullable=True)
    op.alter_column('audit_events', 'entity_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UUID string of the affected entity',
               existing_nullable=True)
    op.alter_column('audit_events', 'entity_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Type of affected entity, e.g. 'identity', 'api_key'",
               existing_nullable=True)
    op.alter_column('audit_events', 'event_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='e.g. identity.enrolled, api_key.created, liveness.failed',
               existing_nullable=False)
    op.alter_column('audit_events', 'actor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Platform user who triggered this event; null for automated actions',
               existing_nullable=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='active | inactive | archived',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('applications', 'environment',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='development | staging | production',
               existing_nullable=False,
               existing_server_default=sa.text("'production'::character varying"))
    op.drop_index(op.f('ix_aaas_api_keys_application_id'), table_name='aaas_api_keys')
    op.alter_column('aaas_api_keys', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='active | revoked | rotated',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('aaas_api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of most recent successful authentication',
               existing_nullable=True)
    op.alter_column('aaas_api_keys', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='List of permitted scopes',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('aaas_api_keys', 'hashed_secret',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hash of the full API key — plaintext never stored',
               existing_nullable=False)
    op.alter_column('aaas_api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='First 12 chars of key used for DB lookup',
               existing_nullable=False)
    op.alter_column('aaas_api_keys', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Human-readable label, e.g. 'Production iOS SDK'",
               existing_nullable=False)
    # ### end Alembic commands ###
